name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "master"
    tags:
      - "!*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build binary
        run: go build -o dist/aws-auth -ldflags="-s -w -X main.version=$(git describe --tags)" .

      - name: Sanity check version
        run: ./dist/aws-auth --version

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install goimports
        run: |-
          cd "$(mktemp -d)"
          go get -u golang.org/x/tools/cmd/goimports
          rm -rf "$PWD"

      - name: Lint code
        run: make style
